export const courses = [
  {
    id: 'life-insurance-fundamentals',
    title: 'Life Insurance Fundamentals',
    category: 'Life Insurance',
    level: 'Beginner',
    duration: '4h 30m',
    videos: 12,
    thumbnail: 'https://images.unsplash.com/photo-1554224155-6726b3ff858f?w=600&q=80',
    description: 'Master the core concepts of life insurance products, underwriting, and claims processing for BFSI professionals.',
    instructor: 'Priya Sharma',
    badge: 'Popular',
    badgeColor: 'bg-red/10 text-red',
    videoIds: ['life-101', 'life-102', 'life-103'],
  },
  {
    id: 'health-insurance-deep-dive',
    title: 'Health Insurance Deep Dive',
    category: 'Health Insurance',
    level: 'Intermediate',
    duration: '6h 15m',
    videos: 18,
    thumbnail: 'https://images.unsplash.com/photo-1576091160550-2173dba999ef?w=600&q=80',
    description: 'Comprehensive coverage of health insurance products, cashless claims, TPA operations and regulatory compliance.',
    instructor: 'Rajesh Kumar',
    badge: 'New',
    badgeColor: 'bg-blue-100 text-blue-600',
    videoIds: ['health-101', 'health-102'],
  },
  {
    id: 'motor-insurance-mastery',
    title: 'Motor Insurance Mastery',
    category: 'General Insurance',
    level: 'Intermediate',
    duration: '3h 45m',
    videos: 10,
    thumbnail: 'https://images.unsplash.com/photo-1449965408869-eaa3f722e40d?w=600&q=80',
    description: 'End-to-end motor insurance course covering OD, third-party, add-ons, survey, and settlement.',
    instructor: 'Ananya Iyer',
    badge: 'Trending',
    badgeColor: 'bg-green-100 text-green-700',
    videoIds: ['motor-101', 'motor-102'],
  },
  {
    id: 'irdai-regulations',
    title: 'IRDAI Regulations & Compliance',
    category: 'Regulatory',
    level: 'Advanced',
    duration: '5h 00m',
    videos: 14,
    thumbnail: 'https://images.unsplash.com/photo-1450101499163-c8848c66ca85?w=600&q=80',
    description: 'Navigate IRDAI circulars, compliance requirements, and regulatory frameworks for insurance entities.',
    instructor: 'Vikram Nair',
    badge: 'Required',
    badgeColor: 'bg-red/10 text-red',
    videoIds: ['reg-101', 'reg-102'],
  },
  {
    id: 'bancassurance-sales',
    title: 'Bancassurance & Cross-Selling',
    category: 'Sales',
    level: 'Beginner',
    duration: '2h 30m',
    videos: 8,
    thumbnail: 'https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?w=600&q=80',
    description: 'Learn bancassurance models, effective cross-selling techniques, and customer-centric advisory approaches.',
    instructor: 'Meera Pillai',
    badge: 'Popular',
    badgeColor: 'bg-red/10 text-red',
    videoIds: ['sales-101', 'sales-102'],
  },
  {
    id: 'claims-excellence',
    title: 'Claims Excellence Program',
    category: 'Claims',
    level: 'Advanced',
    duration: '7h 00m',
    videos: 20,
    thumbnail: 'https://images.unsplash.com/photo-1568992688065-536aad8a12f6?w=600&q=80',
    description: 'Advanced claims management — fraud detection, litigation, re-insurance recoveries, and NPS improvement.',
    instructor: 'Arjun Mehta',
    badge: 'Advanced',
    badgeColor: 'bg-purple-100 text-purple-700',
    videoIds: ['claims-101', 'claims-102'],
  },
]

// Add your iframe embed code to each embedCode field
export const videos = [
  { id: 'life-101', title: 'Introduction to Term Life Insurance', courseId: 'life-insurance-fundamentals', duration: '18:24', embedCode: '', description: 'Understanding term plans, sum assured, premium calculation, and key exclusions.', tags: ['Life', 'Term', 'Beginner'] },
  { id: 'life-102', title: 'Whole Life vs Endowment Plans', courseId: 'life-insurance-fundamentals', duration: '22:10', embedCode: '', description: 'Comparing whole life and endowment policies — features, benefits, and suitability.', tags: ['Life', 'Endowment'] },
  { id: 'life-103', title: 'ULIPs — Unit Linked Insurance Plans', courseId: 'life-insurance-fundamentals', duration: '26:45', embedCode: '', description: 'How ULIPs work, fund options, charges, and regulatory guidelines.', tags: ['Life', 'ULIP'] },
  { id: 'health-101', title: 'Cashless Hospitalisation Explained', courseId: 'health-insurance-deep-dive', duration: '22:10', embedCode: '', description: 'Step-by-step walkthrough of the cashless claims process and TPA coordination.', tags: ['Health', 'Claims'] },
  { id: 'health-102', title: 'Pre-existing Diseases & Waiting Periods', courseId: 'health-insurance-deep-dive', duration: '19:30', embedCode: '', description: 'Understanding PED clauses, waiting period rules, and IRDAI standardisation.', tags: ['Health', 'Underwriting'] },
  { id: 'motor-101', title: 'Motor OD vs Third Party Coverage', courseId: 'motor-insurance-mastery', duration: '15:45', embedCode: '', description: 'Differences between OD and TP policies, compulsory covers, and IDV calculation.', tags: ['Motor'] },
  { id: 'motor-102', title: 'Survey & Loss Assessment', courseId: 'motor-insurance-mastery', duration: '20:15', embedCode: '', description: 'Motor survey process, loss assessment methods, and settlement workflows.', tags: ['Motor', 'Claims'] },
  { id: 'reg-101', title: 'Key IRDAI Circulars of 2024', courseId: 'irdai-regulations', duration: '28:00', embedCode: '', description: 'Summary of all major IRDAI circulars issued in 2024 and their compliance impact.', tags: ['Regulatory', 'IRDAI'] },
  { id: 'reg-102', title: 'Insurance Act — Key Provisions', courseId: 'irdai-regulations', duration: '32:20', embedCode: '', description: 'Critical sections of the Insurance Act 1938 every professional must know.', tags: ['Regulatory'] },
  { id: 'sales-101', title: 'Bancassurance Models in India', courseId: 'bancassurance-sales', duration: '17:50', embedCode: '', description: 'Corporate agency, referral, and open architecture bancassurance models explained.', tags: ['Sales'] },
  { id: 'sales-102', title: 'Needs-Based Selling for Insurance', courseId: 'bancassurance-sales', duration: '21:00', embedCode: '', description: 'Customer profiling, needs analysis, and solution mapping for insurance products.', tags: ['Sales'] },
  { id: 'claims-101', title: 'Claims Fraud Detection Techniques', courseId: 'claims-excellence', duration: '24:30', embedCode: '', description: 'Red flags, investigation techniques, and technology tools for fraud detection.', tags: ['Claims', 'Fraud'] },
  { id: 'claims-102', title: 'Re-Insurance & Recoveries', courseId: 'claims-excellence', duration: '19:45', embedCode: '', description: 'Subrogation, contribution, and re-insurance recovery processes in large claims.', tags: ['Claims'] },
]

export const promotions = [
  { id: 'promo-1', title: 'Early Bird Access', subtitle: 'Get 3 months free on annual plan', description: 'Enrol your entire BFSI team before June 30 and unlock premium courses at no extra cost.', cta: 'Claim Offer', expiresAt: '30 Jun 2025', badge: 'Limited Time' },
  { id: 'promo-2', title: 'IRDAI Exam Prep Bundle', subtitle: 'All regulatory courses in one package', description: 'Get the complete IRDAI compliance & exam preparation bundle — 40% off for corporate accounts.', cta: 'Get Bundle', expiresAt: '31 Jul 2025', badge: '40% Off' },
  { id: 'promo-3', title: 'New Agent Onboarding', subtitle: 'Free starter courses for new joiners', description: 'All new agents get free access to the Fundamentals track — Life, Health & Motor basics included.', cta: 'Start Free', expiresAt: 'Ongoing', badge: 'Free' },
]

export const policyVideos = [
  { id: 'policy-1', title: 'IRDAI Bima Sugam Platform — What It Means for Agents', date: 'May 2025', duration: '12:30', embedCode: '', tag: 'Regulatory Update', tagColor: 'bg-red/10 text-red', summary: 'Deep dive into the new Bima Sugam digital marketplace and its implications for distribution.' },
  { id: 'policy-2', title: 'New Health Insurance Standardisation Norms', date: 'April 2025', duration: '18:00', embedCode: '', tag: 'Policy Change', tagColor: 'bg-amber-100 text-amber-700', summary: "IRDAI's standardisation of health insurance terms — what changes for customers and insurers." },
  { id: 'policy-3', title: 'Motor Insurance Surcharge Rules 2025', date: 'March 2025', duration: '10:45', embedCode: '', tag: 'Compliance', tagColor: 'bg-blue-100 text-blue-700', summary: 'Updated motor surcharge guidelines and how to apply them in underwriting decisions.' },
  { id: 'policy-4', title: 'Anti-Money Laundering Updates for Insurers', date: 'February 2025', duration: '24:15', embedCode: '', tag: 'Compliance', tagColor: 'bg-blue-100 text-blue-700', summary: 'Latest AML/KYC requirements from IRDAI and best practices for implementation.' },
]

export const categories = ['All', 'Life Insurance', 'Health Insurance', 'General Insurance', 'Regulatory', 'Sales', 'Claims']

export const stats = [
  { value: '50+', label: 'Expert Courses' },
  { value: '200+', label: 'Video Lessons' },
  { value: '10,000+', label: 'Professionals Trained' },
  { value: '98%', label: 'Completion Rate' },
]
